### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/react-stylesheet#8]
I'd like to deprecate this package entirely and publish new code under that name — https://github.com/prometheusresearch/react-stylesheet which is more thoughtful and useful implementation of styling for React components.

What do you think, @Swivelgames?

**Comment by Swivelgames** [comment]
Hey @andreypopp , It looks like a great alternative. Do we know what the overall impact is going to be on current dependent projects?

**Comment by andreypopp** [comment]
In going to bump minor version so being under 1.0 means it won't affect
current dependent projects if they follow semver.

**Comment by Swivelgames** [comment]
Sounds good to me!
